#!/bin/sh

umount_device()
{
    n_devices=$(($(df -h | wc -l) - 1))
    selected_row=$(df -h | tail -n $n_devices | rofi -dmenu -p "Select the device to umount" -lines $n_devices)
    mount_point=$(echo "$selected_row" | awk '{print $6}')

    if [ -s "$mount_point" ]; then
        if umount "$mount_point" && rmdir "$mount_point" ; then
            notify_cmd="notify-send \"device umounted, now you can remove it safely\" -i \"SCRIPT_PATH/usb_icon.png\""
            su -c "$notify_cmd" USERNAME
        fi
    fi
}

mount_device()
{
    n_devices=$(($(df -h | wc -l) - 1))
    rofi_cmd="rofi -dmenu -p \"Device '$2 $1' detected. Select the action\" -lines $n_devices"
    answer=$(printf "mount\nignore" | su -c "$rofi_cmd" USERNAME)

    if [ "$answer" = "mount" ]; then
        mount_point="/mnt/$2"
        mkdir "$mount_point"
        if mount "$1" "$mount_point" ; then
            notify_cmd="notify-send \"device mounted\" -i \"SCRIPT_PATH/usb_icon.png\""
            su -c "$notify_cmd" USERNAME
        fi
    fi
}

export DISPLAY=:0

while getopts 'd:u' op ; do
    case $op in
        d) dev_desc=$(echo "$OPTARG" | cut -f1 -d":")
           dev_part=$(echo "$OPTARG" | cut -f2 -d":")

           mount_device "$dev_desc" "$dev_part" ;;

        u) umount_device ;;
        *) ;;
    esac
done

exit 0
