name: usb-rofi check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Static analysis
        run: shellcheck src/usb-rofi.in
